### ISSUE TITLE
Not working on 1.38

### ISSUE THREAD

**Issue by cooperdk** [octfx/mediawiki-extension-WebP#9]
This extension is faulty on v1.38.

Using the classic uploader, an error occurs, as does any successfully uploaded image (with a third party tool like the multi upload tool) when accessing the new files page. 

In addition to this, the script required some adjustments to be operable, including a specialized compilation of Imagemagick which is not supported on server OS's. Webp is typically not supported by imagemagick yet - so I suggest you find another solution for conversion.

Uploading:

[4e433e98dae0c07ebea52be7] /wiki/Speciel:Upload Error: Call to a member function isError() on bool
Backtrace:

from /home/spademanns/public_html/includes/filerepo/file/File.php(1318)
```
#0 /home/spademanns/public_html/includes/filerepo/file/File.php(1258): File->generateAndSaveThumb()
#1 /home/spademanns/public_html/extensions/WebP/includes/Repo/LocalWebPFile.php(97): File->transform()
#2 /home/spademanns/public_html/includes/gallery/TraditionalImageGallery.php(129): MediaWiki\Extension\WebP\Repo\LocalWebPFile->transform()
#3 /home/spademanns/public_html/includes/specials/SpecialUpload.php(892): TraditionalImageGallery->toHTML()
#4 /home/spademanns/public_html/includes/specials/SpecialUpload.php(474): SpecialUpload->getDupeWarning()
#5 /home/spademanns/public_html/includes/specials/SpecialUpload.php(572): SpecialUpload->showUploadWarning()
#6 /home/spademanns/public_html/includes/specials/SpecialUpload.php(244): SpecialUpload->processUpload()
#7 /home/spademanns/public_html/includes/specialpage/SpecialPage.php(671): SpecialUpload->execute()
#8 /home/spademanns/public_html/includes/specialpage/SpecialPageFactory.php(1378): SpecialPage->run()
#9 /home/spademanns/public_html/includes/MediaWiki.php(315): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#10 /home/spademanns/public_html/includes/MediaWiki.php(910): MediaWiki->performRequest()
#11 /home/spademanns/public_html/includes/MediaWiki.php(564): MediaWiki->main()
#12 /home/spademanns/public_html/index.php(53): MediaWiki->run()
#13 /home/spademanns/public_html/index.php(46): wfIndexMain()
#14 {main}

```

Visiting new files page:

```
[aaf9da2b3c646d70853e899e] /wiki/Speciel:Nye_filer Error: Call to a member function isError() on bool
Backtrace:

from /home/spademanns/public_html/includes/filerepo/file/File.php(1318)
#0 /home/spademanns/public_html/includes/filerepo/file/File.php(1258): File->generateAndSaveThumb()
#1 /home/spademanns/public_html/extensions/WebP/includes/Repo/LocalWebPFile.php(97): File->transform()
#2 /home/spademanns/public_html/includes/gallery/TraditionalImageGallery.php(129): MediaWiki\Extension\WebP\Repo\LocalWebPFile->transform()
#3 /home/spademanns/public_html/includes/specials/pagers/NewFilesPager.php(176): TraditionalImageGallery->toHTML()
#4 /home/spademanns/public_html/includes/pager/IndexPager.php(641): NewFilesPager->getEndBody()
#5 /home/spademanns/public_html/includes/specials/SpecialNewFiles.php(137): IndexPager->getBody()
#6 /home/spademanns/public_html/includes/specialpage/SpecialPage.php(671): SpecialNewFiles->execute()
#7 /home/spademanns/public_html/includes/specialpage/SpecialPageFactory.php(1378): SpecialPage->run()
#8 /home/spademanns/public_html/includes/MediaWiki.php(315): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#9 /home/spademanns/public_html/includes/MediaWiki.php(910): MediaWiki->performRequest()
#10 /home/spademanns/public_html/includes/MediaWiki.php(564): MediaWiki->main()
#11 /home/spademanns/public_html/index.php(53): MediaWiki->run()
#12 /home/spademanns/public_html/index.php(46): wfIndexMain()
#13 {main}
```

**Comment by octfx** [comment]
Thanks for reporting. Did you use master or develop?  
I'm pretty sure that this error is fixed in develop.

As for imagick: Currently not documented, but if `cwebp` is installed it is picked before trying to use imagick.

**Comment by cooperdk** [comment]
I can confirm it is working when using the develop branch.

I wasn't aware of it using cwebp, I just don't understand since it was originally installed but the extension errored out until I had re-compiled imagick with webp support (???) so are you sure cwebp is actually used?

**Comment by octfx** [comment]
The extension checks if imagick is available and errors out if its not, but tries to use cwepb first.

https://github.com/octfx/mediawiki-extension-WebP/blob/debda861c8b04cb86c5e194dc4ce0087e3a81419/includes/WebPTransformer.php#L215-L225

I don't really know why I did it this way, seems like a good refactor candidate.

**Comment by cooperdk** [comment]
Still not working when uploading a new image (development branch).

```
[26bfa8026321e41779bd1230] /wiki/Speciel:Upload TypeError: substr() expects parameter 1 to be string, bool given

Backtrace:

from /home/spademanns/public_html/extensions/WebP/includes/Hooks/ThumbnailHooks.php(119)
#0 /home/spademanns/public_html/extensions/WebP/includes/Hooks/ThumbnailHooks.php(119): substr()
#1 /home/spademanns/public_html/includes/HookContainer/HookContainer.php(160): MediaWiki\Extension\WebP\Hooks\ThumbnailHooks->onThumbnailBeforeProduceHTML()
#2 /home/spademanns/public_html/includes/HookContainer/HookRunner.php(3816): MediaWiki\HookContainer\HookContainer->run()
#3 /home/spademanns/public_html/includes/media/ThumbnailImage.php(221): MediaWiki\HookContainer\HookRunner->onThumbnailBeforeProduceHTML()
#4 /home/spademanns/public_html/includes/Linker.php(473): ThumbnailImage->toHtml()
#5 /home/spademanns/public_html/includes/parser/Parser.php(5479): Linker::makeImageLink()
#6 /home/spademanns/public_html/includes/parser/Parser.php(2679): Parser->makeImage()
#7 /home/spademanns/public_html/includes/parser/Parser.php(2426): Parser->handleInternalLinks2()
#8 /home/spademanns/public_html/includes/parser/Parser.php(1608): Parser->handleInternalLinks()
#9 /home/spademanns/public_html/includes/parser/Parser.php(697): Parser->internalParse()
#10 /home/spademanns/public_html/includes/content/WikitextContentHandler.php(294): Parser->parse()
#11 /home/spademanns/public_html/includes/content/ContentHandler.php(1705): WikitextContentHandler->fillParserOutput()
#12 /home/spademanns/public_html/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#13 /home/spademanns/public_html/extensions/SpamBlacklist/includes/SpamBlacklistHooks.php(239): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#14 /home/spademanns/public_html/includes/HookContainer/HookContainer.php(160): SpamBlacklistHooks->onUploadVerifyUpload()
#15 /home/spademanns/public_html/includes/HookContainer/HookRunner.php(4039): MediaWiki\HookContainer\HookContainer->run()
#16 /home/spademanns/public_html/includes/upload/UploadBase.php(944): MediaWiki\HookContainer\HookRunner->onUploadVerifyUpload()
#17 /home/spademanns/public_html/includes/specials/SpecialUpload.php(613): UploadBase->performUpload()
#18 /home/spademanns/public_html/includes/specials/SpecialUpload.php(244): SpecialUpload->processUpload()
#19 /home/spademanns/public_html/includes/specialpage/SpecialPage.php(671): SpecialUpload->execute()
#20 /home/spademanns/public_html/includes/specialpage/SpecialPageFactory.php(1378): SpecialPage->run()
#21 /home/spademanns/public_html/includes/MediaWiki.php(315): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#22 /home/spademanns/public_html/includes/MediaWiki.php(910): MediaWiki->performRequest()
#23 /home/spademanns/public_html/includes/MediaWiki.php(564): MediaWiki->main()
#24 /home/spademanns/public_html/index.php(53): MediaWiki->run()
#25 /home/spademanns/public_html/index.php(46): wfIndexMain()
#26 {main}
```
